name: Generate Documentation with pdoc

on: 
  push:
    branches:
      - main
    paths:
      - '**.py'
jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        cd app && pip install -r requirements.txt

    - name: Generate Documentation
      run: |
        pdoc --html --output-dir docs your_package_name

    - name: Commit and Push Documentation
      env:
        GIT_EMAIL: ${{ secrets.GH_EMAIL }}
        GIT_NAME: ${{ secrets.GH_NAME }}
      run: |
        git config --global user.email "${GH_EMAIL}"
        git config --global user.name "${GH_NAME}"
        git add docs/
        git commit -m "Update documentation"
        git push
